//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using RationesCurare7.Properties;

#pragma warning disable 1591

namespace RationesCurare7.maionemikyWS {
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="EmailSendingSoap", Namespace="http://www.maionemiky.it/")]
    public partial class EmailSending : SoapHttpClientProtocol {
        
        private SendOrPostCallback ComparaDBRCOperationCompleted;
        
        private SendOrPostCallback VersioneDBOperationCompleted;
        
        private SendOrPostCallback OttieniUltimoDBRCOperationCompleted;
        
        private SendOrPostCallback SonoLicenziatoOperationCompleted;
        
        private SendOrPostCallback RecuperaPswRC_SixOperationCompleted;
        
        private SendOrPostCallback GiaEsisteArchivioFotoOperationCompleted;
        
        private SendOrPostCallback AggiornaUtenteOperationCompleted;
        
        private SendOrPostCallback DeZippaDBRCOperationCompleted;
        
        private SendOrPostCallback UploadFileFullOperationCompleted;
        
        private SendOrPostCallback UploadFileOperationCompleted;
        
        private SendOrPostCallback UploadFileRCOperationCompleted;
        
        private SendOrPostCallback UploadFileRC_simpleOperationCompleted;
        
        private SendOrPostCallback CreaDBPerRCOperationCompleted;
        
        private SendOrPostCallback CreaDBPerRC_simpleOperationCompleted;
        
        private SendOrPostCallback ControllaCredenzialiProgOperationCompleted;
        
        private SendOrPostCallback ControllaCredenzialiRC_simpleOperationCompleted;
        
        private SendOrPostCallback ControllaCredenzialiRCOperationCompleted;
        
        private SendOrPostCallback MandaMailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmailSending() {
            this.Url = Settings.Default.RationesCurare7_maionemikyWS_EmailSending;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComparaDBRCCompletedEventHandler ComparaDBRCCompleted;
        
        /// <remarks/>
        public event VersioneDBCompletedEventHandler VersioneDBCompleted;
        
        /// <remarks/>
        public event OttieniUltimoDBRCCompletedEventHandler OttieniUltimoDBRCCompleted;
        
        /// <remarks/>
        public event SonoLicenziatoCompletedEventHandler SonoLicenziatoCompleted;
        
        /// <remarks/>
        public event RecuperaPswRC_SixCompletedEventHandler RecuperaPswRC_SixCompleted;
        
        /// <remarks/>
        public event GiaEsisteArchivioFotoCompletedEventHandler GiaEsisteArchivioFotoCompleted;
        
        /// <remarks/>
        public event AggiornaUtenteCompletedEventHandler AggiornaUtenteCompleted;
        
        /// <remarks/>
        public event DeZippaDBRCCompletedEventHandler DeZippaDBRCCompleted;
        
        /// <remarks/>
        public event UploadFileFullCompletedEventHandler UploadFileFullCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event UploadFileRCCompletedEventHandler UploadFileRCCompleted;
        
        /// <remarks/>
        public event UploadFileRC_simpleCompletedEventHandler UploadFileRC_simpleCompleted;
        
        /// <remarks/>
        public event CreaDBPerRCCompletedEventHandler CreaDBPerRCCompleted;
        
        /// <remarks/>
        public event CreaDBPerRC_simpleCompletedEventHandler CreaDBPerRC_simpleCompleted;
        
        /// <remarks/>
        public event ControllaCredenzialiProgCompletedEventHandler ControllaCredenzialiProgCompleted;
        
        /// <remarks/>
        public event ControllaCredenzialiRC_simpleCompletedEventHandler ControllaCredenzialiRC_simpleCompleted;
        
        /// <remarks/>
        public event ControllaCredenzialiRCCompletedEventHandler ControllaCredenzialiRCCompleted;
        
        /// <remarks/>
        public event MandaMailCompletedEventHandler MandaMailCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/ComparaDBRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public Comparazione ComparaDBRC(string yyyyMMddHHmmss, string email, string psw) {
            object[] results = this.Invoke("ComparaDBRC", new object[] {
                        yyyyMMddHHmmss,
                        email,
                        psw});
            return ((Comparazione)(results[0]));
        }
        
        /// <remarks/>
        public void ComparaDBRCAsync(string yyyyMMddHHmmss, string email, string psw) {
            this.ComparaDBRCAsync(yyyyMMddHHmmss, email, psw, null);
        }
        
        /// <remarks/>
        public void ComparaDBRCAsync(string yyyyMMddHHmmss, string email, string psw, object userState) {
            if ((this.ComparaDBRCOperationCompleted == null)) {
                this.ComparaDBRCOperationCompleted = new SendOrPostCallback(this.OnComparaDBRCOperationCompleted);
            }
            this.InvokeAsync("ComparaDBRC", new object[] {
                        yyyyMMddHHmmss,
                        email,
                        psw}, this.ComparaDBRCOperationCompleted, userState);
        }
        
        private void OnComparaDBRCOperationCompleted(object arg) {
            if ((this.ComparaDBRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ComparaDBRCCompleted(this, new ComparaDBRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/VersioneDB", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public DateTime VersioneDB(string email, string psw) {
            object[] results = this.Invoke("VersioneDB", new object[] {
                        email,
                        psw});
            return ((DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void VersioneDBAsync(string email, string psw) {
            this.VersioneDBAsync(email, psw, null);
        }
        
        /// <remarks/>
        public void VersioneDBAsync(string email, string psw, object userState) {
            if ((this.VersioneDBOperationCompleted == null)) {
                this.VersioneDBOperationCompleted = new SendOrPostCallback(this.OnVersioneDBOperationCompleted);
            }
            this.InvokeAsync("VersioneDB", new object[] {
                        email,
                        psw}, this.VersioneDBOperationCompleted, userState);
        }
        
        private void OnVersioneDBOperationCompleted(object arg) {
            if ((this.VersioneDBCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.VersioneDBCompleted(this, new VersioneDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/OttieniUltimoDBRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        [return: XmlElement(DataType="base64Binary")]
        public byte[] OttieniUltimoDBRC(string yyyyMMddHHmmss, string email, string psw) {
            object[] results = this.Invoke("OttieniUltimoDBRC", new object[] {
                        yyyyMMddHHmmss,
                        email,
                        psw});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void OttieniUltimoDBRCAsync(string yyyyMMddHHmmss, string email, string psw) {
            this.OttieniUltimoDBRCAsync(yyyyMMddHHmmss, email, psw, null);
        }
        
        /// <remarks/>
        public void OttieniUltimoDBRCAsync(string yyyyMMddHHmmss, string email, string psw, object userState) {
            if ((this.OttieniUltimoDBRCOperationCompleted == null)) {
                this.OttieniUltimoDBRCOperationCompleted = new SendOrPostCallback(this.OnOttieniUltimoDBRCOperationCompleted);
            }
            this.InvokeAsync("OttieniUltimoDBRC", new object[] {
                        yyyyMMddHHmmss,
                        email,
                        psw}, this.OttieniUltimoDBRCOperationCompleted, userState);
        }
        
        private void OnOttieniUltimoDBRCOperationCompleted(object arg) {
            if ((this.OttieniUltimoDBRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.OttieniUltimoDBRCCompleted(this, new OttieniUltimoDBRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/SonoLicenziato", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public Licenza SonoLicenziato(string Utente, string Codice) {
            object[] results = this.Invoke("SonoLicenziato", new object[] {
                        Utente,
                        Codice});
            return ((Licenza)(results[0]));
        }
        
        /// <remarks/>
        public void SonoLicenziatoAsync(string Utente, string Codice) {
            this.SonoLicenziatoAsync(Utente, Codice, null);
        }
        
        /// <remarks/>
        public void SonoLicenziatoAsync(string Utente, string Codice, object userState) {
            if ((this.SonoLicenziatoOperationCompleted == null)) {
                this.SonoLicenziatoOperationCompleted = new SendOrPostCallback(this.OnSonoLicenziatoOperationCompleted);
            }
            this.InvokeAsync("SonoLicenziato", new object[] {
                        Utente,
                        Codice}, this.SonoLicenziatoOperationCompleted, userState);
        }
        
        private void OnSonoLicenziatoOperationCompleted(object arg) {
            if ((this.SonoLicenziatoCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.SonoLicenziatoCompleted(this, new SonoLicenziatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/RecuperaPswRC_Six", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool RecuperaPswRC_Six(string Psw, string Email) {
            object[] results = this.Invoke("RecuperaPswRC_Six", new object[] {
                        Psw,
                        Email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaPswRC_SixAsync(string Psw, string Email) {
            this.RecuperaPswRC_SixAsync(Psw, Email, null);
        }
        
        /// <remarks/>
        public void RecuperaPswRC_SixAsync(string Psw, string Email, object userState) {
            if ((this.RecuperaPswRC_SixOperationCompleted == null)) {
                this.RecuperaPswRC_SixOperationCompleted = new SendOrPostCallback(this.OnRecuperaPswRC_SixOperationCompleted);
            }
            this.InvokeAsync("RecuperaPswRC_Six", new object[] {
                        Psw,
                        Email}, this.RecuperaPswRC_SixOperationCompleted, userState);
        }
        
        private void OnRecuperaPswRC_SixOperationCompleted(object arg) {
            if ((this.RecuperaPswRC_SixCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.RecuperaPswRC_SixCompleted(this, new RecuperaPswRC_SixCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/GiaEsisteArchivioFoto", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool GiaEsisteArchivioFoto(string descrizione) {
            object[] results = this.Invoke("GiaEsisteArchivioFoto", new object[] {
                        descrizione});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GiaEsisteArchivioFotoAsync(string descrizione) {
            this.GiaEsisteArchivioFotoAsync(descrizione, null);
        }
        
        /// <remarks/>
        public void GiaEsisteArchivioFotoAsync(string descrizione, object userState) {
            if ((this.GiaEsisteArchivioFotoOperationCompleted == null)) {
                this.GiaEsisteArchivioFotoOperationCompleted = new SendOrPostCallback(this.OnGiaEsisteArchivioFotoOperationCompleted);
            }
            this.InvokeAsync("GiaEsisteArchivioFoto", new object[] {
                        descrizione}, this.GiaEsisteArchivioFotoOperationCompleted, userState);
        }
        
        private void OnGiaEsisteArchivioFotoOperationCompleted(object arg) {
            if ((this.GiaEsisteArchivioFotoCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.GiaEsisteArchivioFotoCompleted(this, new GiaEsisteArchivioFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/AggiornaUtente", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool AggiornaUtente(UtenteProgramma u) {
            object[] results = this.Invoke("AggiornaUtente", new object[] {
                        u});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AggiornaUtenteAsync(UtenteProgramma u) {
            this.AggiornaUtenteAsync(u, null);
        }
        
        /// <remarks/>
        public void AggiornaUtenteAsync(UtenteProgramma u, object userState) {
            if ((this.AggiornaUtenteOperationCompleted == null)) {
                this.AggiornaUtenteOperationCompleted = new SendOrPostCallback(this.OnAggiornaUtenteOperationCompleted);
            }
            this.InvokeAsync("AggiornaUtente", new object[] {
                        u}, this.AggiornaUtenteOperationCompleted, userState);
        }
        
        private void OnAggiornaUtenteOperationCompleted(object arg) {
            if ((this.AggiornaUtenteCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.AggiornaUtenteCompleted(this, new AggiornaUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/DeZippaDBRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool DeZippaDBRC(string PathFile) {
            object[] results = this.Invoke("DeZippaDBRC", new object[] {
                        PathFile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeZippaDBRCAsync(string PathFile) {
            this.DeZippaDBRCAsync(PathFile, null);
        }
        
        /// <remarks/>
        public void DeZippaDBRCAsync(string PathFile, object userState) {
            if ((this.DeZippaDBRCOperationCompleted == null)) {
                this.DeZippaDBRCOperationCompleted = new SendOrPostCallback(this.OnDeZippaDBRCOperationCompleted);
            }
            this.InvokeAsync("DeZippaDBRC", new object[] {
                        PathFile}, this.DeZippaDBRCOperationCompleted, userState);
        }
        
        private void OnDeZippaDBRCOperationCompleted(object arg) {
            if ((this.DeZippaDBRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.DeZippaDBRCCompleted(this, new DeZippaDBRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/UploadFileFull", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultatoFull UploadFileFull(string MapPath_, string Directory_, CredenzialiDiAccesso Credenziali, CredenzialiDiAccessoRC CredenzialiRC, [XmlElement(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("UploadFileFull", new object[] {
                        MapPath_,
                        Directory_,
                        Credenziali,
                        CredenzialiRC,
                        f,
                        fileName});
            return ((CredenzialiRisultatoFull)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileFullAsync(string MapPath_, string Directory_, CredenzialiDiAccesso Credenziali, CredenzialiDiAccessoRC CredenzialiRC, byte[] f, string fileName) {
            this.UploadFileFullAsync(MapPath_, Directory_, Credenziali, CredenzialiRC, f, fileName, null);
        }
        
        /// <remarks/>
        public void UploadFileFullAsync(string MapPath_, string Directory_, CredenzialiDiAccesso Credenziali, CredenzialiDiAccessoRC CredenzialiRC, byte[] f, string fileName, object userState) {
            if ((this.UploadFileFullOperationCompleted == null)) {
                this.UploadFileFullOperationCompleted = new SendOrPostCallback(this.OnUploadFileFullOperationCompleted);
            }
            this.InvokeAsync("UploadFileFull", new object[] {
                        MapPath_,
                        Directory_,
                        Credenziali,
                        CredenzialiRC,
                        f,
                        fileName}, this.UploadFileFullOperationCompleted, userState);
        }
        
        private void OnUploadFileFullOperationCompleted(object arg) {
            if ((this.UploadFileFullCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.UploadFileFullCompleted(this, new UploadFileFullCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/UploadFile", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultato UploadFile(CredenzialiDiAccesso Credenziali, [XmlElement(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        Credenziali,
                        f,
                        fileName});
            return ((CredenzialiRisultato)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(CredenzialiDiAccesso Credenziali, byte[] f, string fileName) {
            this.UploadFileAsync(Credenziali, f, fileName, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(CredenzialiDiAccesso Credenziali, byte[] f, string fileName, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        Credenziali,
                        f,
                        fileName}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/UploadFileRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultato UploadFileRC(CredenzialiDiAccessoRC Credenziali, [XmlElement(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("UploadFileRC", new object[] {
                        Credenziali,
                        f,
                        fileName});
            return ((CredenzialiRisultato)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileRCAsync(CredenzialiDiAccessoRC Credenziali, byte[] f, string fileName) {
            this.UploadFileRCAsync(Credenziali, f, fileName, null);
        }
        
        /// <remarks/>
        public void UploadFileRCAsync(CredenzialiDiAccessoRC Credenziali, byte[] f, string fileName, object userState) {
            if ((this.UploadFileRCOperationCompleted == null)) {
                this.UploadFileRCOperationCompleted = new SendOrPostCallback(this.OnUploadFileRCOperationCompleted);
            }
            this.InvokeAsync("UploadFileRC", new object[] {
                        Credenziali,
                        f,
                        fileName}, this.UploadFileRCOperationCompleted, userState);
        }
        
        private void OnUploadFileRCOperationCompleted(object arg) {
            if ((this.UploadFileRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.UploadFileRCCompleted(this, new UploadFileRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/UploadFileRC_simple", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultatoFull UploadFileRC_simple(string yyyyMMddHHmmss, string Utente, string Psw, [XmlElement(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("UploadFileRC_simple", new object[] {
                        yyyyMMddHHmmss,
                        Utente,
                        Psw,
                        f,
                        fileName});
            return ((CredenzialiRisultatoFull)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileRC_simpleAsync(string yyyyMMddHHmmss, string Utente, string Psw, byte[] f, string fileName) {
            this.UploadFileRC_simpleAsync(yyyyMMddHHmmss, Utente, Psw, f, fileName, null);
        }
        
        /// <remarks/>
        public void UploadFileRC_simpleAsync(string yyyyMMddHHmmss, string Utente, string Psw, byte[] f, string fileName, object userState) {
            if ((this.UploadFileRC_simpleOperationCompleted == null)) {
                this.UploadFileRC_simpleOperationCompleted = new SendOrPostCallback(this.OnUploadFileRC_simpleOperationCompleted);
            }
            this.InvokeAsync("UploadFileRC_simple", new object[] {
                        yyyyMMddHHmmss,
                        Utente,
                        Psw,
                        f,
                        fileName}, this.UploadFileRC_simpleOperationCompleted, userState);
        }
        
        private void OnUploadFileRC_simpleOperationCompleted(object arg) {
            if ((this.UploadFileRC_simpleCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.UploadFileRC_simpleCompleted(this, new UploadFileRC_simpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/CreaDBPerRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool CreaDBPerRC(CredenzialiDiAccessoRC CredenzialiRC) {
            object[] results = this.Invoke("CreaDBPerRC", new object[] {
                        CredenzialiRC});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreaDBPerRCAsync(CredenzialiDiAccessoRC CredenzialiRC) {
            this.CreaDBPerRCAsync(CredenzialiRC, null);
        }
        
        /// <remarks/>
        public void CreaDBPerRCAsync(CredenzialiDiAccessoRC CredenzialiRC, object userState) {
            if ((this.CreaDBPerRCOperationCompleted == null)) {
                this.CreaDBPerRCOperationCompleted = new SendOrPostCallback(this.OnCreaDBPerRCOperationCompleted);
            }
            this.InvokeAsync("CreaDBPerRC", new object[] {
                        CredenzialiRC}, this.CreaDBPerRCOperationCompleted, userState);
        }
        
        private void OnCreaDBPerRCOperationCompleted(object arg) {
            if ((this.CreaDBPerRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.CreaDBPerRCCompleted(this, new CreaDBPerRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/CreaDBPerRC_simple", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public bool CreaDBPerRC_simple(string Utente, string Psw) {
            object[] results = this.Invoke("CreaDBPerRC_simple", new object[] {
                        Utente,
                        Psw});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreaDBPerRC_simpleAsync(string Utente, string Psw) {
            this.CreaDBPerRC_simpleAsync(Utente, Psw, null);
        }
        
        /// <remarks/>
        public void CreaDBPerRC_simpleAsync(string Utente, string Psw, object userState) {
            if ((this.CreaDBPerRC_simpleOperationCompleted == null)) {
                this.CreaDBPerRC_simpleOperationCompleted = new SendOrPostCallback(this.OnCreaDBPerRC_simpleOperationCompleted);
            }
            this.InvokeAsync("CreaDBPerRC_simple", new object[] {
                        Utente,
                        Psw}, this.CreaDBPerRC_simpleOperationCompleted, userState);
        }
        
        private void OnCreaDBPerRC_simpleOperationCompleted(object arg) {
            if ((this.CreaDBPerRC_simpleCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.CreaDBPerRC_simpleCompleted(this, new CreaDBPerRC_simpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/ControllaCredenzialiProg", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultato ControllaCredenzialiProg(CredenzialiDiAccesso Credenziali) {
            object[] results = this.Invoke("ControllaCredenzialiProg", new object[] {
                        Credenziali});
            return ((CredenzialiRisultato)(results[0]));
        }
        
        /// <remarks/>
        public void ControllaCredenzialiProgAsync(CredenzialiDiAccesso Credenziali) {
            this.ControllaCredenzialiProgAsync(Credenziali, null);
        }
        
        /// <remarks/>
        public void ControllaCredenzialiProgAsync(CredenzialiDiAccesso Credenziali, object userState) {
            if ((this.ControllaCredenzialiProgOperationCompleted == null)) {
                this.ControllaCredenzialiProgOperationCompleted = new SendOrPostCallback(this.OnControllaCredenzialiProgOperationCompleted);
            }
            this.InvokeAsync("ControllaCredenzialiProg", new object[] {
                        Credenziali}, this.ControllaCredenzialiProgOperationCompleted, userState);
        }
        
        private void OnControllaCredenzialiProgOperationCompleted(object arg) {
            if ((this.ControllaCredenzialiProgCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ControllaCredenzialiProgCompleted(this, new ControllaCredenzialiProgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/ControllaCredenzialiRC_simple", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultato ControllaCredenzialiRC_simple(string Utente, string Psw) {
            object[] results = this.Invoke("ControllaCredenzialiRC_simple", new object[] {
                        Utente,
                        Psw});
            return ((CredenzialiRisultato)(results[0]));
        }
        
        /// <remarks/>
        public void ControllaCredenzialiRC_simpleAsync(string Utente, string Psw) {
            this.ControllaCredenzialiRC_simpleAsync(Utente, Psw, null);
        }
        
        /// <remarks/>
        public void ControllaCredenzialiRC_simpleAsync(string Utente, string Psw, object userState) {
            if ((this.ControllaCredenzialiRC_simpleOperationCompleted == null)) {
                this.ControllaCredenzialiRC_simpleOperationCompleted = new SendOrPostCallback(this.OnControllaCredenzialiRC_simpleOperationCompleted);
            }
            this.InvokeAsync("ControllaCredenzialiRC_simple", new object[] {
                        Utente,
                        Psw}, this.ControllaCredenzialiRC_simpleOperationCompleted, userState);
        }
        
        private void OnControllaCredenzialiRC_simpleOperationCompleted(object arg) {
            if ((this.ControllaCredenzialiRC_simpleCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ControllaCredenzialiRC_simpleCompleted(this, new ControllaCredenzialiRC_simpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/ControllaCredenzialiRC", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public CredenzialiRisultato ControllaCredenzialiRC(CredenzialiDiAccessoRC CredenzialiRC) {
            object[] results = this.Invoke("ControllaCredenzialiRC", new object[] {
                        CredenzialiRC});
            return ((CredenzialiRisultato)(results[0]));
        }
        
        /// <remarks/>
        public void ControllaCredenzialiRCAsync(CredenzialiDiAccessoRC CredenzialiRC) {
            this.ControllaCredenzialiRCAsync(CredenzialiRC, null);
        }
        
        /// <remarks/>
        public void ControllaCredenzialiRCAsync(CredenzialiDiAccessoRC CredenzialiRC, object userState) {
            if ((this.ControllaCredenzialiRCOperationCompleted == null)) {
                this.ControllaCredenzialiRCOperationCompleted = new SendOrPostCallback(this.OnControllaCredenzialiRCOperationCompleted);
            }
            this.InvokeAsync("ControllaCredenzialiRC", new object[] {
                        CredenzialiRC}, this.ControllaCredenzialiRCOperationCompleted, userState);
        }
        
        private void OnControllaCredenzialiRCOperationCompleted(object arg) {
            if ((this.ControllaCredenzialiRCCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ControllaCredenzialiRCCompleted(this, new ControllaCredenzialiRCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://www.maionemiky.it/MandaMail", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public string MandaMail(string Oggetto, string Testo, string Destinatario) {
            object[] results = this.Invoke("MandaMail", new object[] {
                        Oggetto,
                        Testo,
                        Destinatario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MandaMailAsync(string Oggetto, string Testo, string Destinatario) {
            this.MandaMailAsync(Oggetto, Testo, Destinatario, null);
        }
        
        /// <remarks/>
        public void MandaMailAsync(string Oggetto, string Testo, string Destinatario, object userState) {
            if ((this.MandaMailOperationCompleted == null)) {
                this.MandaMailOperationCompleted = new SendOrPostCallback(this.OnMandaMailOperationCompleted);
            }
            this.InvokeAsync("MandaMail", new object[] {
                        Oggetto,
                        Testo,
                        Destinatario}, this.MandaMailOperationCompleted, userState);
        }
        
        private void OnMandaMailOperationCompleted(object arg) {
            if ((this.MandaMailCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.MandaMailCompleted(this, new MandaMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public enum Comparazione {
        
        /// <remarks/>
        Uguale,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        AccessoNonAutizzato,
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public enum Licenza {
        
        /// <remarks/>
        Fallito,
        
        /// <remarks/>
        RegistratoOK,
        
        /// <remarks/>
        CodiceInesistente,
        
        /// <remarks/>
        GiaRegistrato,
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public partial class UtenteProgramma {
        
        private string programmaField;
        
        private string utenteField;
        
        private DateTime versioneField;
        
        /// <remarks/>
        public string Programma {
            get {
                return this.programmaField;
            }
            set {
                this.programmaField = value;
            }
        }
        
        /// <remarks/>
        public string Utente {
            get {
                return this.utenteField;
            }
            set {
                this.utenteField = value;
            }
        }
        
        /// <remarks/>
        public DateTime Versione {
            get {
                return this.versioneField;
            }
            set {
                this.versioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public partial class CredenzialiRisultatoFull {
        
        private CredenzialiRisultato credenzialiRisultato_Field;
        
        private string erroreField;
        
        /// <remarks/>
        public CredenzialiRisultato CredenzialiRisultato_ {
            get {
                return this.credenzialiRisultato_Field;
            }
            set {
                this.credenzialiRisultato_Field = value;
            }
        }
        
        /// <remarks/>
        public string Errore {
            get {
                return this.erroreField;
            }
            set {
                this.erroreField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public enum CredenzialiRisultato {
        
        /// <remarks/>
        TuttoOK,
        
        /// <remarks/>
        Presente_PasswordErrata,
        
        /// <remarks/>
        Assente,
        
        /// <remarks/>
        Errore,
        
        /// <remarks/>
        ProgrammaNonAutorizzato,
        
        /// <remarks/>
        FileInviato,
        
        /// <remarks/>
        DBSulServerEPiuRecente,
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public partial class CredenzialiDiAccessoRC {
        
        private string utenteField;
        
        private string pswField;
        
        /// <remarks/>
        public string Utente {
            get {
                return this.utenteField;
            }
            set {
                this.utenteField = value;
            }
        }
        
        /// <remarks/>
        public string Psw {
            get {
                return this.pswField;
            }
            set {
                this.pswField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.3056.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.maionemiky.it/")]
    public partial class CredenzialiDiAccesso {
        
        private string nomeApplicazioneField;
        
        /// <remarks/>
        public string NomeApplicazione {
            get {
                return this.nomeApplicazioneField;
            }
            set {
                this.nomeApplicazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void ComparaDBRCCompletedEventHandler(object sender, ComparaDBRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ComparaDBRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComparaDBRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Comparazione Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Comparazione)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void VersioneDBCompletedEventHandler(object sender, VersioneDBCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class VersioneDBCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersioneDBCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void OttieniUltimoDBRCCompletedEventHandler(object sender, OttieniUltimoDBRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class OttieniUltimoDBRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OttieniUltimoDBRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void SonoLicenziatoCompletedEventHandler(object sender, SonoLicenziatoCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SonoLicenziatoCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SonoLicenziatoCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Licenza Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Licenza)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void RecuperaPswRC_SixCompletedEventHandler(object sender, RecuperaPswRC_SixCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class RecuperaPswRC_SixCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaPswRC_SixCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void GiaEsisteArchivioFotoCompletedEventHandler(object sender, GiaEsisteArchivioFotoCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GiaEsisteArchivioFotoCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GiaEsisteArchivioFotoCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void AggiornaUtenteCompletedEventHandler(object sender, AggiornaUtenteCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AggiornaUtenteCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggiornaUtenteCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void DeZippaDBRCCompletedEventHandler(object sender, DeZippaDBRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DeZippaDBRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeZippaDBRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadFileFullCompletedEventHandler(object sender, UploadFileFullCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class UploadFileFullCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileFullCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultatoFull Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultatoFull)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class UploadFileCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadFileRCCompletedEventHandler(object sender, UploadFileRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class UploadFileRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadFileRC_simpleCompletedEventHandler(object sender, UploadFileRC_simpleCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class UploadFileRC_simpleCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileRC_simpleCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultatoFull Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultatoFull)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void CreaDBPerRCCompletedEventHandler(object sender, CreaDBPerRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class CreaDBPerRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreaDBPerRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void CreaDBPerRC_simpleCompletedEventHandler(object sender, CreaDBPerRC_simpleCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class CreaDBPerRC_simpleCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreaDBPerRC_simpleCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void ControllaCredenzialiProgCompletedEventHandler(object sender, ControllaCredenzialiProgCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ControllaCredenzialiProgCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ControllaCredenzialiProgCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void ControllaCredenzialiRC_simpleCompletedEventHandler(object sender, ControllaCredenzialiRC_simpleCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ControllaCredenzialiRC_simpleCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ControllaCredenzialiRC_simpleCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void ControllaCredenzialiRCCompletedEventHandler(object sender, ControllaCredenzialiRCCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ControllaCredenzialiRCCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ControllaCredenzialiRCCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CredenzialiRisultato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CredenzialiRisultato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    public delegate void MandaMailCompletedEventHandler(object sender, MandaMailCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class MandaMailCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MandaMailCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591