insert into valute (Valuta, Descrizione) values ('DJF', 'Djiboutian Franc');
insert into valute (Valuta, Descrizione) values ('ERN', 'Eritrean Nakfa');
insert into valute (Valuta, Descrizione) values ('ETB', 'Ethiopian Birr');
insert into valute (Valuta, Descrizione) values ('NAD', 'Namibian Dollar');
insert into valute (Valuta, Descrizione) values ('ZAR', 'South African Rand');
insert into valute (Valuta, Descrizione) values ('XAF', 'Central African CFA Franc');
insert into valute (Valuta, Descrizione) values ('GHS', 'Ghanaian Cedi');
insert into valute (Valuta, Descrizione) values ('XDR', 'Special Drawing Rights');
insert into valute (Valuta, Descrizione) values ('AED', 'United Arab Emirates Dirham');
insert into valute (Valuta, Descrizione) values ('BHD', 'Bahraini Dinar');
insert into valute (Valuta, Descrizione) values ('DZD', 'Algerian Dinar');
insert into valute (Valuta, Descrizione) values ('EGP', 'Egyptian Pound');
insert into valute (Valuta, Descrizione) values ('ILS', 'Israeli New Shekel');
insert into valute (Valuta, Descrizione) values ('IQD', 'Iraqi Dinar');
insert into valute (Valuta, Descrizione) values ('JOD', 'Jordanian Dinar');
insert into valute (Valuta, Descrizione) values ('KMF', 'Comorian Franc');
insert into valute (Valuta, Descrizione) values ('KWD', 'Kuwaiti Dinar');
insert into valute (Valuta, Descrizione) values ('LBP', 'Lebanese Pound');
insert into valute (Valuta, Descrizione) values ('LYD', 'Libyan Dinar');
insert into valute (Valuta, Descrizione) values ('MAD', 'Moroccan Dirham');
insert into valute (Valuta, Descrizione) values ('MRU', 'Mauritanian Ouguiya');
insert into valute (Valuta, Descrizione) values ('OMR', 'Omani Rial');
insert into valute (Valuta, Descrizione) values ('QAR', 'Qatari Rial');
insert into valute (Valuta, Descrizione) values ('SAR', 'Saudi Riyal');
insert into valute (Valuta, Descrizione) values ('SDG', 'Sudanese Pound');
insert into valute (Valuta, Descrizione) values ('SOS', 'Somali Shilling');
insert into valute (Valuta, Descrizione) values ('SSP', 'South Sudanese Pound');
insert into valute (Valuta, Descrizione) values ('SYP', 'Syrian Pound');
insert into valute (Valuta, Descrizione) values ('TND', 'Tunisian Dinar');
insert into valute (Valuta, Descrizione) values ('YER', 'Yemeni Rial');
insert into valute (Valuta, Descrizione) values ('CLP', 'Chilean Peso');
insert into valute (Valuta, Descrizione) values ('INR', 'Indian Rupee');
insert into valute (Valuta, Descrizione) values ('TZS', 'Tanzanian Shilling');
insert into valute (Valuta, Descrizione) values ('EUR', 'Euro');
insert into valute (Valuta, Descrizione) values ('AZN', 'Azerbaijani Manat');
insert into valute (Valuta, Descrizione) values ('RUB', 'Russian Ruble');
insert into valute (Valuta, Descrizione) values ('BYN', 'Belarusian Ruble');
insert into valute (Valuta, Descrizione) values ('ZMW', 'Zambian Kwacha');
insert into valute (Valuta, Descrizione) values ('BGN', 'Bulgarian Lev');
insert into valute (Valuta, Descrizione) values ('NGN', 'Nigerian Naira');
insert into valute (Valuta, Descrizione) values ('XOF', 'West African CFA Franc');
insert into valute (Valuta, Descrizione) values ('BDT', 'Bangladeshi Taka');
insert into valute (Valuta, Descrizione) values ('CNY', 'Chinese Yuan');
insert into valute (Valuta, Descrizione) values ('BAM', 'Bosnia-Herzegovina Convertible Mark');
insert into valute (Valuta, Descrizione) values ('UGX', 'Ugandan Shilling');
insert into valute (Valuta, Descrizione) values ('USD', 'US Dollar');
insert into valute (Valuta, Descrizione) values ('CZK', 'Czech Koruna');
insert into valute (Valuta, Descrizione) values ('GBP', 'British Pound');
insert into valute (Valuta, Descrizione) values ('DKK', 'Danish Krone');
insert into valute (Valuta, Descrizione) values ('KES', 'Kenyan Shilling');
insert into valute (Valuta, Descrizione) values ('CHF', 'Swiss Franc');
insert into valute (Valuta, Descrizione) values ('MVR', 'Maldivian Rufiyaa');
insert into valute (Valuta, Descrizione) values ('BTN', 'Bhutanese Ngultrum');
insert into valute (Valuta, Descrizione) values ('XCD', 'East Caribbean Dollar');
insert into valute (Valuta, Descrizione) values ('AUD', 'Australian Dollar');
insert into valute (Valuta, Descrizione) values ('BBD', 'Barbadian Dollar');
insert into valute (Valuta, Descrizione) values ('BIF', 'Burundian Franc');
insert into valute (Valuta, Descrizione) values ('BMD', 'Bermudan Dollar');
insert into valute (Valuta, Descrizione) values ('BSD', 'Bahamian Dollar');
insert into valute (Valuta, Descrizione) values ('BWP', 'Botswanan Pula');
insert into valute (Valuta, Descrizione) values ('BZD', 'Belize Dollar');
insert into valute (Valuta, Descrizione) values ('CAD', 'Canadian Dollar');
insert into valute (Valuta, Descrizione) values ('NZD', 'New Zealand Dollar');
insert into valute (Valuta, Descrizione) values ('FJD', 'Fijian Dollar');
insert into valute (Valuta, Descrizione) values ('FKP', 'Falkland Islands Pound');
insert into valute (Valuta, Descrizione) values ('GIP', 'Gibraltar Pound');
insert into valute (Valuta, Descrizione) values ('GMD', 'Gambian Dalasi');
insert into valute (Valuta, Descrizione) values ('GYD', 'Guyanaese Dollar');
insert into valute (Valuta, Descrizione) values ('HKD', 'Hong Kong Dollar');
insert into valute (Valuta, Descrizione) values ('IDR', 'Indonesian Rupiah');
insert into valute (Valuta, Descrizione) values ('JMD', 'Jamaican Dollar');
insert into valute (Valuta, Descrizione) values ('KYD', 'Cayman Islands Dollar');
insert into valute (Valuta, Descrizione) values ('LRD', 'Liberian Dollar');
insert into valute (Valuta, Descrizione) values ('MGA', 'Malagasy Ariary');
insert into valute (Valuta, Descrizione) values ('MOP', 'Macanese Pataca');
insert into valute (Valuta, Descrizione) values ('MUR', 'Mauritian Rupee');
insert into valute (Valuta, Descrizione) values ('MWK', 'Malawian Kwacha');
insert into valute (Valuta, Descrizione) values ('MYR', 'Malaysian Ringgit');
insert into valute (Valuta, Descrizione) values ('PGK', 'Papua New Guinean Kina');
insert into valute (Valuta, Descrizione) values ('PHP', 'Philippine Piso');
insert into valute (Valuta, Descrizione) values ('PKR', 'Pakistani Rupee');
insert into valute (Valuta, Descrizione) values ('RWF', 'Rwandan Franc');
insert into valute (Valuta, Descrizione) values ('SBD', 'Solomon Islands Dollar');
insert into valute (Valuta, Descrizione) values ('SCR', 'Seychellois Rupee');
insert into valute (Valuta, Descrizione) values ('SEK', 'Swedish Krona');
insert into valute (Valuta, Descrizione) values ('SGD', 'Singapore Dollar');
insert into valute (Valuta, Descrizione) values ('SHP', 'Saint Helena Pound');
insert into valute (Valuta, Descrizione) values ('SLL', 'Sierra Leonean Leone');
insert into valute (Valuta, Descrizione) values ('ANG', 'Netherlands Antillean Guilder');
insert into valute (Valuta, Descrizione) values ('SZL', 'Swazi Lilangeni');
insert into valute (Valuta, Descrizione) values ('TOP', 'Tongan Paʻanga');
insert into valute (Valuta, Descrizione) values ('TTD', 'Trinidad and Tobago Dollar');
insert into valute (Valuta, Descrizione) values ('VUV', 'Vanuatu Vatu');
insert into valute (Valuta, Descrizione) values ('WST', 'Samoan Tala');
insert into valute (Valuta, Descrizione) values ('ARS', 'Argentine Peso');
insert into valute (Valuta, Descrizione) values ('BOB', 'Bolivian Boliviano');
insert into valute (Valuta, Descrizione) values ('BRL', 'Brazilian Real');
insert into valute (Valuta, Descrizione) values ('COP', 'Colombian Peso');
insert into valute (Valuta, Descrizione) values ('CRC', 'Costa Rican Colón');
insert into valute (Valuta, Descrizione) values ('CUP', 'Cuban Peso');
insert into valute (Valuta, Descrizione) values ('DOP', 'Dominican Peso');
insert into valute (Valuta, Descrizione) values ('GTQ', 'Guatemalan Quetzal');
insert into valute (Valuta, Descrizione) values ('HNL', 'Honduran Lempira');
insert into valute (Valuta, Descrizione) values ('MXN', 'Mexican Peso');
insert into valute (Valuta, Descrizione) values ('NIO', 'Nicaraguan Córdoba');
insert into valute (Valuta, Descrizione) values ('PAB', 'Panamanian Balboa');
insert into valute (Valuta, Descrizione) values ('PEN', 'Peruvian Sol');
insert into valute (Valuta, Descrizione) values ('PYG', 'Paraguayan Guarani');
insert into valute (Valuta, Descrizione) values ('UYU', 'Uruguayan Peso');
insert into valute (Valuta, Descrizione) values ('VES', 'Venezuelan Bolívar');
insert into valute (Valuta, Descrizione) values ('IRR', 'Iranian Rial');
insert into valute (Valuta, Descrizione) values ('GNF', 'Guinean Franc');
insert into valute (Valuta, Descrizione) values ('CDF', 'Congolese Franc');
insert into valute (Valuta, Descrizione) values ('HTG', 'Haitian Gourde');
insert into valute (Valuta, Descrizione) values ('XPF', 'CFP Franc');
insert into valute (Valuta, Descrizione) values ('HRK', 'Croatian Kuna');
insert into valute (Valuta, Descrizione) values ('HUF', 'Hungarian Forint');
insert into valute (Valuta, Descrizione) values ('AMD', 'Armenian Dram');
insert into valute (Valuta, Descrizione) values ('ISK', 'Icelandic Króna');
insert into valute (Valuta, Descrizione) values ('JPY', 'Japanese Yen');
insert into valute (Valuta, Descrizione) values ('GEL', 'Georgian Lari');
insert into valute (Valuta, Descrizione) values ('CVE', 'Cape Verdean Escudo');
insert into valute (Valuta, Descrizione) values ('KZT', 'Kazakhstani Tenge');
insert into valute (Valuta, Descrizione) values ('KHR', 'Cambodian Riel');
insert into valute (Valuta, Descrizione) values ('KPW', 'North Korean Won');
insert into valute (Valuta, Descrizione) values ('KRW', 'South Korean Won');
insert into valute (Valuta, Descrizione) values ('KGS', 'Kyrgystani Som');
insert into valute (Valuta, Descrizione) values ('AOA', 'Angolan Kwanza');
insert into valute (Valuta, Descrizione) values ('LAK', 'Laotian Kip');
insert into valute (Valuta, Descrizione) values ('MZN', 'Mozambican Metical');
insert into valute (Valuta, Descrizione) values ('MKD', 'Macedonian Denar');
insert into valute (Valuta, Descrizione) values ('MNT', 'Mongolian Tugrik');
insert into valute (Valuta, Descrizione) values ('BND', 'Brunei Dollar');
insert into valute (Valuta, Descrizione) values ('MMK', 'Myanmar Kyat');
insert into valute (Valuta, Descrizione) values ('NOK', 'Norwegian Krone');
insert into valute (Valuta, Descrizione) values ('NPR', 'Nepalese Rupee');
insert into valute (Valuta, Descrizione) values ('AWG', 'Aruban Florin');
insert into valute (Valuta, Descrizione) values ('SRD', 'Surinamese Dollar');
insert into valute (Valuta, Descrizione) values ('PLN', 'Polish Zloty');
insert into valute (Valuta, Descrizione) values ('AFN', 'Afghan Afghani');
insert into valute (Valuta, Descrizione) values ('STN', 'São Tomé and Príncipe Dobra');
insert into valute (Valuta, Descrizione) values ('MDL', 'Moldovan Leu');
insert into valute (Valuta, Descrizione) values ('RON', 'Romanian Leu');
insert into valute (Valuta, Descrizione) values ('UAH', 'Ukrainian Hryvnia');
insert into valute (Valuta, Descrizione) values ('LKR', 'Sri Lankan Rupee');
insert into valute (Valuta, Descrizione) values ('ALL', 'Albanian Lek');
insert into valute (Valuta, Descrizione) values ('RSD', 'Serbian Dinar');
insert into valute (Valuta, Descrizione) values ('TJS', 'Tajikistani Somoni');
insert into valute (Valuta, Descrizione) values ('THB', 'Thai Baht');
insert into valute (Valuta, Descrizione) values ('TMT', 'Turkmenistani Manat');
insert into valute (Valuta, Descrizione) values ('TRY', 'Turkish Lira');
insert into valute (Valuta, Descrizione) values ('UZS', 'Uzbekistani Som');
insert into valute (Valuta, Descrizione) values ('VND', 'Vietnamese Dong');
insert into valute (Valuta, Descrizione) values ('TWD', 'New Taiwan Dollar');
